### ISSUE TITLE
Drive your JS Addiction

### ISSUE THREAD

**Issue by diegocrzt** [jorgediazsamaniego/kaelthasjs#1]
Please comment what is about this amazing repository

**Comment by jorgediazsa** [comment]
If you don't know why you need this amazing repository then you don't deserve the power of Kael'thasJS

**Comment by diegocrzt** [comment]
Then a least commit something, I need to fork this plz

**Comment by diegocrzt** [comment]
Consider #2

**Comment by diegocrzt** [comment]
Wiiiiiiiiiii
